// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(map)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(map)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(map)/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../app/(map)/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/debug/route-loading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug/route-loading">> = Specific
  const handler = {} as typeof import("../../../app/debug/route-loading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my">> = Specific
  const handler = {} as typeof import("../../../app/my/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/support/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/support/feedback">> = Specific
  const handler = {} as typeof import("../../../app/my/support/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/support/guides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/support/guides">> = Specific
  const handler = {} as typeof import("../../../app/my/support/guides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/support/notices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/support/notices">> = Specific
  const handler = {} as typeof import("../../../app/my/support/notices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/support/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my/support/report">> = Specific
  const handler = {} as typeof import("../../../app/my/support/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/walk/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/walk/result">> = Specific
  const handler = {} as typeof import("../../../app/walk/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../../app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fountains/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fountains">> = Specific
  const handler = {} as typeof import("../../../app/api/fountains/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/images/[imageId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/[imageId]">> = Specific
  const handler = {} as typeof import("../../../app/api/images/[imageId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/images/direct-upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/direct-upload">> = Specific
  const handler = {} as typeof import("../../../app/api/images/direct-upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/petpois/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/petpois">> = Specific
  const handler = {} as typeof import("../../../app/api/petpois/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/routes/recommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routes/recommend">> = Specific
  const handler = {} as typeof import("../../../app/api/routes/recommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/tmap/pedestrian/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tmap/pedestrian">> = Specific
  const handler = {} as typeof import("../../../app/api/tmap/pedestrian/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/tmap/pois/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tmap/pois">> = Specific
  const handler = {} as typeof import("../../../app/api/tmap/pois/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/tmap/reverse-geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tmap/reverse-geocode">> = Specific
  const handler = {} as typeof import("../../../app/api/tmap/reverse-geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/trash-bins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trash-bins">> = Specific
  const handler = {} as typeof import("../../../app/api/trash-bins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(map)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(map)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/my/support/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/my/support">> = Specific
  const handler = {} as typeof import("../../../app/my/support/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
