export const SNAP_LOCAL_BACKWARD_SEGMENTS = 30;
export const SNAP_LOCAL_FORWARD_SEGMENTS = 120;
export const SNAP_FALLBACK_DISTANCE_M = 35;

export const ROUTE_REDRAW_MIN_MOVE_M = 5;
export const ROUTE_OFF_ROUTE_DISTANCE_M = 25;
export const ROUTE_OFF_ROUTE_CONNECTOR_MAX_M = 45;
export const ROUTE_REROUTE_PROMPT_DISTANCE_M = 60;
export const ROUTE_REROUTE_PROMPT_COOLDOWN_MS = 20_000;
export const ROUTE_MIN_RENDERABLE_LENGTH_M = 3;

