export const SNAP_LOCAL_BACKWARD_SEGMENTS = 30;
export const SNAP_LOCAL_FORWARD_SEGMENTS = 120;
export const SNAP_FALLBACK_DISTANCE_M = 35;

export const ROUTE_REDRAW_MIN_MOVE_M = 5;
export const ROUTE_OFF_ROUTE_DISTANCE_M = 25;
export const ROUTE_OFF_ROUTE_CONNECTOR_MAX_M = 45;
export const ROUTE_REROUTE_PROMPT_DISTANCE_M = 60;
export const ROUTE_REROUTE_PROMPT_COOLDOWN_MS = 20_000;
export const ROUTE_ARRIVAL_PROMPT_DISTANCE_M = 25;
export const ROUTE_ARRIVAL_PROMPT_EXIT_DISTANCE_M = 60;
export const ROUTE_ARRIVAL_ROUND_TRIP_ENDPOINT_DISTANCE_M = 20;
export const ROUTE_ARRIVAL_ROUND_TRIP_PROGRESS_RATIO = 0.85;
export const ROUTE_MIN_RENDERABLE_LENGTH_M = 3;

export const TRACKING_MAX_FORWARD_JUMP_M = 180;
export const TRACKING_MAX_BACKWARD_JUMP_M = 18;
export const TRACKING_PROGRESS_SOFT_FORWARD_M = 22;
export const TRACKING_PROGRESS_SOFT_BACKWARD_M = 6;
export const TRACKING_PROGRESS_SEGMENT_JUMP_PENALTY = 5;
export const TRACKING_HEADING_WEIGHT = 0.16;
export const TRACKING_HEADING_HARD_REJECT_DEG = 145;
export const TRACKING_AMBIGUITY_SCORE_DELTA = 6;
export const TRACKING_PENDING_CONFIRM_COUNT = 2;
export const TRACKING_PENDING_CONFIRM_DISTANCE_M = 10;
